---
title: "ESM 244 Lab 2"
author: "K. Dobbs"
date: "2023-01-19"
output: html_document
---

```{r setup, echo=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE)


library(tidyverse)
library(palmerpenguins)
library(AICcmodavg)
library(equatiomatic)

```


# Predicting penguin mass

```{r}
penguins_clean <- penguins %>% 
  drop_na() %>% 
  rename(mass = body_mass_g,
         bill_l = bill_length_mm,
         bill_d = bill_depth_mm,
         flip_l = flipper_length_mm)

mdl_1 <- lm(mass ~ bill_l + bill_d + flip_l + species + sex + island, 
            data = penguins_clean)
```


```{r}

f1 <- mass ~ bill_l + bill_d + flip_l + species + sex + island

mdl_1 <- lm(f1, data = penguins_clean)

#recognize formula as a specific type of object / variable (in this case f1)

f2 <- mass ~ bill_l + bill_d + flip_l + species + sex
mdl_2 <- lm(f2, data = penguins_clean)

f3 <- mass ~ bill_d + flip_l + species + sex
mdl_3 <- lm(f3, data = penguins_clean)

AIC(mdl_1, mdl_2, mdl_3)
BIC(mdl_1, mdl_2, mdl_3)

AICc(mdl_1)

aictab(list(mdl_1, mdl_2, mdl_3))
bictab(list(mdl_1, mdl_2, mdl_3))

```

#compare models using k-fold cross validation

```{r}
folds <- 10 #break dataset into 10 chunks iterative. take chunk1 out, generate coefficients using 90% of the data, and then test it against the stuff we set aside. Then put that back in, take the next 10% chunk out and do it again
fold_vec <- rep(1:folds, length.out = nrow(penguins_clean))

set.seed(42)
penguins_fold <- penguins_clean %>% 
  mutate(group = sample(fold_vec, size =n(), replace = FALSE))

table(penguins_fold$group)

#vector with labels to say which bin/folder we're putting in, we need to randomly assign using set seed
```

##first fold


```{r}
test_df <- penguins_fold %>% 
  filter(group == 1)

train_df <- penguins_fold %>% 
  filter(group !=1)
```



```{r}
calc_rmse <- function(x, y) {
  rmse <- (x -y)^2 %>% 
    mean() %>% 
    sqrt()
  return(rmse)
}
```


```{r}
training_mdl_1 <- lm(f1, data = train_df)

training_mdl_2 <- lm(f2, data = train_df)

training_mdl_3 <- lm(f3, data = train_df)

predict_test <- test_df %>% 
  mutate(model1 = predict(training_mdl_1, test_df),
         model2 = predict(training_mdl_2, test_df),
         model3 = predict(training_mdl_3, test_df))


rmse_predict_test <- predict_test %>% 
  summarize(rmse_mdl_1 = calc_rmse(model1, mass),
            rmse_mdl_2 = calc_rmse(model2, mass),
            rmse_mdl_3 = calc_rmse(model3, mass))

rmse_predict_test

#rmse take the different between known and predicted, square the differences to emphasize the big ones and de-emphasize the smaller ones, take the average of those squares, and then square root it

#what we've done so far is the first line of the marble example from lecture
#it would be annoying to do all the rest of the lines from that example, so we're going to make it automatic???

#i got different numbers than him

```

```{r}
rmse_df <- data.frame()

for(i in 1:folds) {
  kfold_test_df <- penguins_fold %>% 
    filter(group == i)
  kfold_train_df <- penguins_fold %>% 
    filter(group != i)
  
  kfold_mdl_1 <- lm(f1, data = kfold_train_df)
  kfold_mdl_2 <- lm(f2, data = kfold_train_df)
  kfold_mdl_3 <- lm(f3, data = kfold_train_df)
  
  kfold_pred_df <- kfold_test_df %>% 
    mutate(mdl_1 = predict(kfold_mdl_1, kfold_test_df),
           mdl_2 = predict(kfold_mdl_2, kfold_test_df),
           mdl_3 = predict(kfold_mdl_3, kfold_test_df))
  kfold_rmse <- kfold_pred_df %>% 
    summarize(rmse_mdl_1 = calc_rmse(mdl_1, mass),
              rmse_mdl_2 = calc_rmse(mdl_2, mass),
              rmse_mdl_3 = calc_rmse(mdl_3, mass),
              test_gp = i)
  rmse_df <- bind_rows(rmse_df, kfold_rmse)
}

rmse_df

rmse_df %>% 
  summarize(mean_rmse_mdl_1 = mean(rmse_mdl_1),
            mean_rmse_mdl_2 = mean(rmse_mdl_2),
            mean_rmse_mdl_3 = mean(rmse_mdl_3))


```


##Finalize the Model

```{r}
final_mdl <- lm(f2, data = penguins_clean)
```


our final model:
`r equatiomatic::extract_eq(mdl_2, wrap=TRUE)`

and with coefficients in place:
`r equatiomatic::extract_eq(mdl_2, wrap=TRUE, use_coefs = TRUE)`






